name: Build and Push Docker Image for Keygen Service

on:
  push:
    branches:
      - 20-move-keygen-service
    tags:
      - keygen-service-*


jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./services/keygen-service

    steps:
      - name: Checkout the Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download Release From sign-protocols
        uses: dsaltares/fetch-gh-release-asset@1.1.1
        with:
          repo: 'zargarzadehm/sign-protocols'
          version: 'latest'
          regex: true
          file: 'rosenTss-linux-*'
          target: './services/keygen-service/bin/'

      - name: Move the Files
        run: |
          mv ./docker/production.yaml ./config/
          mv ./docker/custom-environment-variables.yaml ./config/
          7z x ./bin/rosenTss-linux-* -obin/ && rm -rf ./bin/*.zip
          mv ./bin/rosenTss-* ./bin/rosenTss

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ vars.PLATFORM_LIST || 'linux/amd64' }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: zargarzadehm
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Metadata action
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/zargarzadehm/keygen-service
          tags: |
            type=ref,event=branch
            type=match,pattern=\d.\d.\d

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ vars.PLATFORM_LIST || 'linux/amd64' }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
